### ISSUE TITLE
std::function vs function pointer difference

### ISSUE THREAD

**Issue by cyrush** [LLNL/conduit#1431]
Interesting difference between the function pointer vs std::function interface for allocators:

macOS (clang) with the function pointers - even if the method name was overloaded, we were able to to the following:

```
conduit::utils::register_allocator(HostMemory::allocate, ...)
```

```
//-----------------------------------------------------------------------------
void *
HostMemory::allocate(size_t bytes)
{
  m_total_bytes_alloced += bytes;
  m_alloc_count++;
#if defined(ASCENT_UMPIRE_ENABLED)
  auto &rm = umpire::ResourceManager::getInstance ();
  const int allocator_id = AllocationManager::host_allocator_id();
  umpire::Allocator host_allocator = rm.getAllocator (allocator_id);
  return host_allocator.allocate(bytes);
#else
  return malloc(bytes);
#endif
}


//-----------------------------------------------------------------------------
void *
HostMemory::allocate(size_t items, size_t item_size)
{
  return allocate(items * item_size);
}
```

But with the `std::function` interface, the compiler doesn't figure it out:

```
 /Users/runner/work/ascent/ascent/src/libs/ascent/runtimes/expressions/ascent_memory_manager.cpp:214:44: error: no viable conversion from '<overloaded function type>' to 'handle_alloc_type' (aka 'function<void *(unsigned long, unsigned long)>')
      = conduit::utils::register_allocator(HostMemory::allocate,
                                           ^~~~~~~~~~~~~~~~~~~~
```

**Comment by cyrush** [comment]
This is also breaking spack ci builds with ascent 0.9.3 and conduit 0.9.4

**Comment by cyrush** [comment]
I am fixing this for new ascent release

**Comment by cyrush** [comment]
More discussion:
https://stackoverflow.com/questions/30393285/stdfunction-fails-to-distinguish-overloaded-functions

**Comment by cyrush** [comment]
I tried to add both signatures (std::function and the old function pointer) and compiled against ascent 0.9.3, that approach won't work -- also ends up being ambiguous.

```
 >> 1543    /tmp/root/spack-stage/spack-stage-ascent-0.9.3-tp73uiuwkoxhm7467g3
             ade4r7ik5unpe/spack-src/src/libs/ascent/runtimes/expressions/ascen
             t_memory_manager.cpp:213:43: error: cannot resolve overloaded func
             tion 'allocate' based on conversion to type 'conduit::utils::handl
             e_alloc_type' {aka 'std::function<void*(long unsigned int, long un
             signed int)>'}
```

`std::function` provides flexibility we need and I am working on a fix for the ascent release. I will just constrain spack to not build ascent 0.9.3 with conduit 0.9.4.
